# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'EMR' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SMART', :git => 'git@github.com:smart-on-fhir/Swift-SMART.git', :tag => '2.4.0'
  pod 'SWRevealViewController'
  pod 'SwiftSpinner', '~>0.9'
  pod 'TOWebViewController'
  pod 'XCGLogger', '~> 3.3'
  pod 'ReachabilitySwift', '~> 2.4'
  target 'EMRTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
